---

env:
  es6: true
  node: true


overrides:

  -
    env:
      browser: true
      es6: true
      node: true

    files:
      - 'src/**/*.ts'
    extends:
      - '@matthiaskunnen/eslint-config-typescript-node'

    parser: '@typescript-eslint/parser'

    parserOptions:
      project:
        - tsconfig/tsconfig.lint.json
      ecmaFeatures:
        modules: true
      ecmaVersion: 2020
      sourceType: module

    rules:
      no-console: off
